// This is a placeholder for the CoreML model class
// The actual fastvithd.mlmodelc should be included in the model download
// and this file will be generated by Xcode when compiling the model

import CoreML
import Foundation

/// Placeholder protocol for the FastViTHD CoreML model
/// The actual implementation is generated by Xcode from the .mlmodelc file
@available(iOS 18.2, *)
public class fastvithd {
    
    /// Model input
    public class Input: MLFeatureProvider {
        public var images: MLMultiArray
        
        public var featureNames: Set<String> {
            return Set(["images"])
        }
        
        public func featureValue(for featureName: String) -> MLFeatureValue? {
            if featureName == "images" {
                return MLFeatureValue(multiArray: images)
            }
            return nil
        }
        
        public init(images: MLMultiArray) {
            self.images = images
        }
    }
    
    /// Model output
    public class Output: MLFeatureProvider {
        public let image_features: MLMultiArray
        
        public var featureNames: Set<String> {
            return Set(["image_features"])
        }
        
        public func featureValue(for featureName: String) -> MLFeatureValue? {
            if featureName == "image_features" {
                return MLFeatureValue(multiArray: image_features)
            }
            return nil
        }
        
        public init(image_features: MLMultiArray) {
            self.image_features = image_features
        }
    }
    
    private var model: MLModel
    
    public init() throws {
        // Look for the model in the bundle
        guard let modelURL = Bundle.main.url(forResource: "fastvithd", withExtension: "mlmodelc", subdirectory: "model") else {
            // Try without subdirectory
            guard let url = Bundle.main.url(forResource: "fastvithd", withExtension: "mlmodelc") else {
                throw NSError(domain: "FastVLM", code: 1, userInfo: [
                    NSLocalizedDescriptionKey: "Could not find fastvithd.mlmodelc in bundle"
                ])
            }
            model = try MLModel(contentsOf: url)
            return
        }
        model = try MLModel(contentsOf: modelURL)
    }
    
    public func prediction(images: MLMultiArray) throws -> Output {
        let input = Input(images: images)
        let output = try model.prediction(from: input)
        
        guard let imageFeatures = output.featureValue(for: "image_features")?.multiArrayValue else {
            throw NSError(domain: "FastVLM", code: 2, userInfo: [
                NSLocalizedDescriptionKey: "Could not get image_features from model output"
            ])
        }
        
        return Output(image_features: imageFeatures)
    }
}
